name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploying to production
        if: github.ref == 'refs/heads/master'
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          RM: true
        with:
          source: './build/*'
          target: ${{ secrets.PRODUCTIONPATH }}

      - name: Copying content of build folder to production path folder
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: mv ${{ secrets.PRODUCTIONPATH }}/build/*  ${{ secrets.PRODUCTIONPATH }}
